apiVersion: v1
kind: Service
metadata:
  name: productpage-loadbalancer
  namespace: cdps-27
spec:
  type: LoadBalancer
  selector:
    app: productpage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9095
