apiVersion: v1
kind: Service
metadata:
  name: reviews-service
  namespace: cdps-27
spec:
  selector:
    app: reviews
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9095
  type: ClusterIP
